<a href="https://colab.research.google.com/github/ajrianop/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

Numpy is a library in Python which offers us a lot of tools in order to do a lot of computing in a mathematical sense. We are going to initialize this as follows:

In [1]:
import numpy as np

To see the version on numpy that we are using:

In [2]:
print(np.__version__)

1.21.6


## **Creating an array**

We can create some arrays to use numpy functions:

In [3]:
'''
There are two arrays 1-dimensional and 2-dimensional
'''
arr1=np.array([0,1,2,3,4])
print("This is a 1-dimensional array:\n", arr1)
arr2=np.array([(4,2,3),(9,3,5)])
print("This is a 2-dimensional array:\n", arr2)

This is a 1-dimensional array:
 [0 1 2 3 4]
This is a 2-dimensional array:
 [[4 2 3]
 [9 3 5]]


Let us see some attributes in order to know more about our array. 

In [4]:
#To see the dimension of the arrays
print(f'Dimension of arr1= {arr1.ndim}')
print(f'Dimension of arr2= {arr2.ndim}')

Dimension of arr1= 1
Dimension of arr2= 2


In [5]:
#To see the size of the array
print(f'Size of arr1= {arr1.size}')
print(f'Size of arr2= {arr2.size}')

Size of arr1= 5
Size of arr2= 6


In [6]:
#To see the size of the array
print(f'Shape of arr1= {arr1.shape}')
print(f'Shape of arr2= {arr2.shape}')

Shape of arr1= (5,)
Shape of arr2= (2, 3)


## **Array using the function arange**

According to the uses of memory, we have that taking the usual way to obtain a range of number,and creating an array uses more memory if we use numpy libray.

In [7]:
'''
The module sys provides various functions and variables that are used to
manipulate different parts of the Python runtime environment
'''
import sys
rang1=range(500)
mem_py=sys.getsizeof(3)*len(rang1)
rang2=np.arange(500)
mem_np=rang2.size*rang2.itemsize
print(f"Uses of memory only Python {mem_py}\n Uses of memory with numpy {mem_np}")

Uses of memory only Python 14000
 Uses of memory with numpy 4000


In [8]:
#https://www.youtube.com/watch?v=WxJr143Os-A&ab_channel=AprendeIAconLigdiGonzalez

## **Creating matrices with entries zero, random and empty**

In [9]:
#Generate a matrix 3x3 with zeros
zer=np.zeros((3,3))
print(f'zer = {zer}')
#Generating a matrix 4x4 with random values
ran=np.random.random((4,4))
print(f'ran= {ran}')
#Return a new array of given shape and type, without initializing entries.
emp=np.empty((2,2))
print(f'emp= {emp}')
#Generate a matrix 4x3 with values 6.
ful=np.full((4,3),6)
print(ful)

zer = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ran= [[0.57986285 0.28460729 0.39691645 0.78194777]
 [0.0441513  0.9088604  0.59209426 0.13351123]
 [0.20768506 0.12081571 0.79748123 0.57975058]
 [0.73933857 0.17924311 0.33855375 0.91482773]]
emp= [[5.e-324 5.e-324]
 [5.e-324 0.e+000]]
[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]


## **Slicing array according to the index**

In [10]:
#Generating a range with values from 0 to 32 each four spaces
rang=np.arange(0,32,4)
print(f'Range of values from 0 to 32 with a space of 4 units=\n{rang}')
inter=np.linspace(0,6,13)
print(f'Partition of the interval [0,6] into 13 pieces=\n{inter}')

Range of values from 0 to 32 with a space of 4 units=
[ 0  4  8 12 16 20 24 28]
Partition of the interval [0,6] into 13 pieces=
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6. ]


In [11]:
#We want the type of data stored in each array, so
print('data type of rang: {}'.format(rang.dtype))
print('data type of inter: {}'.format(inter.dtype))

data type of rang: int64
data type of inter: float64


In [12]:
#We can change an element in each entry of an array
array=np.array([2,4,78,12,32,10,9])
print(f'original array: {array}')
array[2]=21
print(f'new array: {array}')

original array: [ 2  4 78 12 32 10  9]
new array: [ 2  4 21 12 32 10  9]


In [13]:
#Slicing the array
array[1:4]

array([ 4, 21, 12])

In [14]:
#Re-writing the values from 2 to 5
print(f'Array given: {array}')
array[2:6]= 14 , 15 , 16 , 17
print(f'New array: {array}')

Array given: [ 2  4 21 12 32 10  9]
New array: [ 2  4 14 15 16 17  9]


In [15]:
#Step slicing array[begin: end: step]
array[1:6:2]

array([ 4, 15, 17])

## **Assign values according to a list related to the index**

In [16]:
#According to the array
arr=np.linspace(10,130,13)
print(f'Array: {arr}')
#We define an index list call select
select=[2,4,9]
new_arr=arr[select]
print(f'Array with the entries according to the list index "select": {new_arr}')
#We can modify all the element considered by select
arr[select]= 10
print(f'Array with new value in the position by "select": {arr}')
arr[select]= 30.0 , 50.0 , 100.0
print(f'Recovering the information in the position by "select": {arr}')

Array: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110. 120. 130.]
Array with the entries according to the list index "select": [ 30.  50. 100.]
Array with new value in the position by "select": [ 10.  20.  10.  40.  10.  60.  70.  80.  90.  10. 110. 120. 130.]
Recovering the information in the position by "select": [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110. 120. 130.]


## **Functions with numpy (mathematical and statistics)**

In statistics we have some relevant functions as the mean, median, mode, standar deviation, between other.



In [17]:
x=np.array([10,20,10,30,40])

In [18]:
#

## ***Exercises:***

1. Create an array with the number from 0 to 15

In [19]:
exer1=np.arange(0,16,1)
exer1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

2. Write the odd number in the array given before

In [20]:
exer2=exer1[::2]
exer2

array([ 0,  2,  4,  6,  8, 10, 12, 14])